export const HANDLE_MAIN_SCREEN = "HANDLE_MAIN_SCREEN";
export const SET_CURRENT_USER_DETAILS = "SET_CURRENT_USER_DETAILS";
export const HANDLE_HOME_SCREEN_SECTION = "HANDLE_HOME_SCREEN_SECTION";
export const HANDLE_ACCOUNT_SCREEN_SECTION = "HANDLE_ACCOUNT_SCREEN_SECTION";
export const HANDLE_SUBCONTENT_SCREEN_SECTION =
  "HANDLE_SUBCONTENT_SCREEN_SECTION";
